name: Release
on:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/rust.yml

  release:
    needs: ci
    uses: Sp0Q1/fracture-cms/.github/workflows/release-app.yaml@main
    with:
      image_name: ghcr.io/${{ github.repository }}
    secrets: inherit
